# Generated by Django 4.1.7 on 2023-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(max_length=100)),
                ("Last_Name", models.CharField(max_length=100)),
                ("DateOfBirth", models.TextField()),
                ("Gender", models.CharField(max_length=100)),
                ("Phone_number", models.IntegerField()),
                ("Email", models.EmailField(max_length=254)),
                ("Department", models.CharField(max_length=100)),
                ("Courses", models.CharField(max_length=100)),
                ("Purpose", models.CharField(max_length=100)),
            ],
        ),
    ]
