# Generated by Django 4.1.7 on 2023-02-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_remove_mydata_courses_remove_mydata_dateofbirth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mydata",
            name="Courses",
            field=models.CharField(default=12.2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mydata",
            name="DateOfBirth",
            field=models.TextField(default=78.23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mydata",
            name="Department",
            field=models.CharField(default=12.55, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mydata",
            name="Email",
            field=models.EmailField(default=12.3, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mydata",
            name="Gender",
            field=models.CharField(default=24.4, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mydata",
            name="Last_Name",
            field=models.CharField(default=12.45, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mydata",
            name="Phone_number",
            field=models.IntegerField(default=23.56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mydata",
            name="Purpose",
            field=models.CharField(default=12.3, max_length=100),
            preserve_default=False,
        ),
    ]
