# Generated by Django 4.1.7 on 2023-02-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_rename_courses_mydata_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mydata",
            name="Gender",
            field=models.CharField(default=12.3, max_length=100),
            preserve_default=False,
        ),
    ]
